### ISSUE TITLE
Create a go-runtime task for service deployment hangs and never completes 

### ISSUE THREAD

**Issue by rymonroe** [triggermesh/runtime-build-tasks#1]
###### Version of Knative
0.8.0

###### Version of Kubernetes
1.14

###### Version of Tekton
0.6.0

###### Expected Behavior
Running 
`tm deploy service lambda-runtime-test -f . --build-template https://raw.githubusercontent.com/triggermesh/runtime-build-tasks/master/aws-lambda/go-runtime.yaml --wait` 
should create Knative service. Attached is the simple main.go I had
 in current directory.
[main.go.txt](https://github.com/triggermesh/runtime-build-tasks/files/3559773/main.go.txt)

##### Actual Behavior
Task hangs and eventually times out after 1 hour. The step-sources/step-dockerfile/step-exports logs were all empty.

**Comment by sebgoa** [comment]
thanks for reporting, we are looking into it

**Comment by tzununbekov** [comment]
@rymonroe could you try to update tm CLI to the [latest](https://github.com/triggermesh/tm/releases/latest) version and try service deployment again? There was breaking changes in Tekton Pipelines v0.6.0 which was not incorporated in the previous tm release

**Comment by rymonroe** [comment]
@tzununbekov I'll give that a try later today and let you know

**Comment by rymonroe** [comment]
Updating to latest tm CLI solved issue. Thanks.
